FROM ckan/ckan-dev:2.12

USER root
RUN mkdir /srv/app/.local && chown ckan /srv/app/.local

RUN pip3 install git+https://github.com/ckan/ckanext-scheming.git@master#egg=ckanext-scheming
RUN pip3 install git+https://github.com/dathere/ckanext-gztr.git@main#egg=ckanext-gztr

RUN pip3 install -U bleach sqlparse

USER ckan

# Clone the extension(s) your are writing for your own project in the `src` folder
# to get them mounted in this image at runtime

# Copy custom initialization scripts
COPY --chown=ckan-sys:ckan-sys docker-entrypoint.d/* /docker-entrypoint.d/

# Apply any patches needed to CKAN core or any of the built extensions (not the
# runtime mounted ones)
COPY --chown=ckan-sys:ckan-sys patches ${APP_DIR}/patches

USER ckan

RUN for d in $APP_DIR/patches/*; do \
        if [ -d $d ]; then \
            for f in `ls $d/*.patch | sort -g`; do \
                cd $SRC_DIR/`basename "$d"` && echo "$0: Applying patch $f to $SRC_DIR/`basename $d`"; patch -p1 < "$f" ; \
            done ; \
        fi ; \
    done
